name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "21"
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: |
        sudo apt install -y openjdk-${{ env.JAVA_VERSION }}-jdk wget unzip
        JAVA_HOME=/usr/lib/jvm/java-${{ env.JAVA_VERSION }}-openjdk-amd64
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "${JAVA_HOME}/bin" >> $GITHUB_PATH
    - name: Set up Android SDK/NDK
      run: |
        nimble -d:GitHubCI setupBuildEnv -Y
    - name: Run tests
      run: |
        nimble -d:GitHubCI test
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: raylib-game-apk
        path: ${{ github.workspace }}/raylib_game.apk
        if-no-files-found: error

  test-windows:
    runs-on: windows-latest
    env:
      JAVA_VERSION: "21"
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: |
        choco install wget
        choco install openjdk --version=${{ env.JAVA_VERSION }}.*
    - name: Set up Android SDK/NDK
      run: |
        nimble -d:GitHubCI setupBuildEnv -Y
    - name: Run tests
      run: |
        nimble -d:GitHubCI test
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: raylib-game-apk-windows
        path: ${{ github.workspace }}\raylib_game.apk
        if-no-files-found: error
